language: go
go_import_path: github.com/guitarpawat/wsp-ecommerce
env:
  global:
  - JYTHON=false
  - DISPLAY=':99.0'
branches:
  only:
  - "/.*/"
jobs:
  include:
  - stage: Backend Test
    name: go 1.10.x
    if: branch != master
    go: 1.10.x
    services: mongodb
    before_install: skip
    install:
    - go get -t -v ./...
    before_script: skip
    script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    after_script: skip
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: Backend Test
    name: go 1.11.x
    if: branch != master
    go: 1.11.x
    services: mongodb
    before_install: skip
    install:
    - go get -t -v ./...
    before_script: skip
    script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    after_script: skip
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: Frontend Test
    name: go 1.10.x
    if: branch != master
    go: 1.10.x
    services: mongodb
    addons:
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
    before_install:
    - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
    - sudo wget --no-verbose http://chromedriver.storage.googleapis.com/$CDVERSION/chromedriver_linux64.zip
    - sudo unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/
    - sudo chmod 777 /usr/bin/chromedriver
    install:
    - sudo -H pip install -r requirements.txt
    before_script:
    - go get -t -v ./...
    - go run main.go -env=CI &
    - google-chrome-stable --no-sandbox --ignore-certificate-errors --headless --window-size=1920,1080
      --disable-gpu --disable-dev-shm-usage --remote-debugging-port=51232 http://localhost:8000 &
    script: robot --variable browser:headlesschrome robot/tests.robot
    after-script: skip
  - stage: Frontend Test
    name: go 1.11.x
    if: branch != master
    go: 1.11.x
    services: mongodb
    addons:
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
    before_install:
    - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
    - sudo wget --no-verbose http://chromedriver.storage.googleapis.com/$CDVERSION/chromedriver_linux64.zip
    - sudo unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/
    - sudo chmod 777 /usr/bin/chromedriver
    install:
    - sudo -H pip install -r requirements.txt
    before_script:
    - go get -t -v ./...
    - go run main.go -env=CI &
    - google-chrome-stable --no-sandbox --ignore-certificate-errors --headless --window-size=1920,1080
      --disable-gpu --disable-dev-shm-usage --remote-debugging-port=51232 http://localhost:8000 &
    script: robot --variable browser:headlesschrome robot/tests.robot
    after-script: skip
  - stage: Deploy Build
    if: branch = master
    script: skip
    deploy: &heroku
      provider: heroku
      api_key:
        secure: lxuvxmXwPVFV934hsQCJ8g+5kC/qYtGmojltWRpVSyoqzs3UlWiONF1a1b32hhqwoTYaV+QccSUa9oBQak/9J0SQdGFst9ouEebHdpDJAvvQjnhr54lvVMExPS7g8cDsiZmDEkDR03IYly87sfJHvE5PtC1NV2Kra6LiU39DhvyzVeeAflMwUoPQT1NfVJGjZLD83NvELVjAMmDk+RzaPXTLWZ9TxgXyev3Gw/li9suUujO2Z29gcbvkGEnOM7ojwVmnEE3U7JN1i+Vzy/7ssStxYFPOwNYNgYIFhfTFSULqHKEMShS5K0Jk+dMzSjZAhcJb6g8oxyCD2ti4GDqgOVwQlm/Shfv4YJoRH+GKN6AgSj8GX2sWiF/iCyw5putk1fl4eMn60LcAxTYMZuVM7LqCPaMxAI4EgRcYkmd42YZlfjkIY0j6IaTggpF30a9BhsIfNtVlqaq9mEknvsJoLmmljyphgDZZub7kWL+k7xt0EFxggkOdV9ZfOHUR9UCi1CuDaFecmYL0gIUG8xgCkHku5kcE2fHIPrTRxjAk5j6it/Bcw7wAmzsa/RqiU9VuoEROCxtJzDcErSUzNzt5uDU93Fg4oGlHXiL4QLaP6HIlDk7ZT/Q/6tN4sNL2qkko5ziFqzlOC0uWKjAdPTcNF7LY50fhk6+ay2MgfQHZqn4=
      app: wsp-ecommerce
      on:
        repo: guitarpawat/wsp-ecommerce
